# Generated by Django 4.1.7 on 2023-03-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='created',
        ),
    ]
